{% set name = "chi2comb-py" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/chi2comb/chi2comb-{{ version }}.tar.gz
  sha256: 1fd5017c059d38c748ffd4416723658e66231e5d91fc2b7faa3db5855219214f

build:
  number: 1
  skip: true  # [py27]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cffi >=1.11.5
    - chi2comb >=0.0.3
    - pip
    - pytest-runner >=4.2
    - python
    - setuptools >=38.4.0
  run:
    - pytest-doctestplus >=0.3.0
    - cffi >=1.11.5
    - chi2comb >=0.0.3
    - pytest >=3.6.3
    - pytest-runner >=4.2
    - python

test:
  imports:
    - chi2comb

about:
  home: https://github.com/limix/chi2comb-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Linear combination of independent noncentral chi-squared random variables'
  dev_url: https://github.com/limix/chi2comb-py

extra:
  recipe-maintainers:
    - Horta
