travis:
  secure:
    BINSTAR_TOKEN: InQw6eRWoxUlaza8PyExuGAxbI3r7WfeOxP6Dt1VPCzH2fi+WcNyzSf/hThIBTgycQ0sFw30EiS2tMQK1rkjGXQElFZJdpcrkvBpAmTIdKFw8Zvp4M6yNVk3p+4HgkJsRsmeaVNM5ULpyJ4Yen6Zya7xZMk5o9UJ6MyQ5a8rW14irQVQVLDMHBM8ClUNtatI7LalLDMM6eIRHOa1pSRiR1rwpAEeimATuHSE/jpyazGanW33LQtwwOMdm6Yyq5u9hCEK9cC4HPATibIDEtvAPMOvP5ju8/EGwOONkotJNqCNHXXgDBaGccswpN9FDX7DZwCJ4I5F7vRlTMXUAlkCkkrxPoxcZ3IIvJj9sPQx0o+quOQAdjl0sufoDdvBHMmhfiiHTu1qwUeOItvQaz/9ZGIxbUJNOkkh5KOT6jnJFCUqVmQ/u4ukwe+DFfbtZ9Q1r3orlMLcs/NGyl1WoKzVrtYw2si7T9GH1Vozu7R4mxXF7b12Bq/Q0XwakR/sA9uAa8kxA0ADIbOpnodzd3zw/0ma0/jqgSRSDfzTxl33hbGiPJzN53FVw3DRgfVLI6RVMWmKZMmEGNI8DHRpLKgnXx9F2yMwV7MyceOGmeQodi6xmyj3wYCydXJnj64yaalp62h3AfPZTPwcmmYYuxFbrvSb1TbZt5waUnuHMInT/Ls=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
